DROP TABLE IF EXISTS adventure;

CREATE TABLE adventure (
  id INT AUTO_INCREMENT PRIMARY KEY,
  price INT NOT NULL DEFAULT NULL,
  category INT NOT NULL DEFAULT NULL,
  name VARCHAR(50) NOT NULL,
  description VARCHAR(500) DEFAULT NULL,
  image VARCHAR(500) DEFAULT NULL,
  date TIMESTAMP DEFAULT NULL,
  max_entrant INT DEFAULT NULL
);
