language: java
services:
  - postgresql
before_install:
  - cd config-server-microservice
  - mvn -q install
  - cd ../eureka-microservice
  - mvn -q install
  - cd ../zuul-server-microservice
  - mvn -q install
  - cd ../adventure-microservice
  - mvn -q install
  - cd ../category-microservice
  - mvn -q install
  - cd ../clientui-microservice
  - mvn -q install
  - cd ../payment-microservice
  - mvn -q install
  - cd ../client-microservice
  - mvn -q install
  - cd ../login-microservice
  - mvn -q install
  - cd ../comment-microservice
  - mvn -q install