language: java
before_install:
  - cd adventure-microservice
  - mvn clean install
  - cd ../category-microservice
  - mvn clean install
  - cd ../clientui-microservice
  - mvn clean install
  - cd ../payment-microservice
  - mvn clean install

