language: java
before_install:
  - cd config-server-microservice
  - mvn clean install
  - cd ../eureka-microservice
  - mvn clean install
  - cd ../zuul-server-microservice
  - mvn clean install
  - cd ../adventure-microservice
  - mvn clean install
  - cd ../category-microservice
  - mvn clean install
  - cd ../clientui-microservice
  - mvn clean install
  - cd ../payment-microservice
  - mvn clean install