DROP TABLE IF EXISTS category;

CREATE TABLE category (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  color VARCHAR(50) DEFAULT NULL
);

INSERT INTO category VALUES(1, 'desert', '#9370DB');
INSERT INTO category VALUES(2, 'hike', '#45AF36');
INSERT INTO category VALUES(3, 'survivor', '#2C8DE3');